version: "1"

volumes:
  pg_dash_data:

services:
  postgresql:
      image: postgres:14
      ports: 
        - 15432:5432
      container_name: postgres_dash
      volumes:
        - pg_dash_data:/var/lib/postgresql/data:rw
      environment:
        POSTGRES_PASSWORD: postgres